### ISSUE TITLE
客户端不能是一个独立程序

### ISSUE THREAD

**Issue by Yelijah** [FlowerBirds/WebSocketExplorer#1]
作者把客户端放到main中另开程序运行，这是javax.websocket的api无法做到的。会报错
![image](https://user-images.githubusercontent.com/33784573/57457489-39b5e080-72a2-11e9-9993-d1d1d608a32e.png)
看下ContainerProvider.getContainer()的实现：
`public static WebSocketContainer getWebSocketContainer() {
         WebSocketContainer wsc = null;
        for (ContainerProvider impl : ServiceLoader.load(ContainerProvider.class)) {
            wsc = impl.getContainer();
            if (wsc != null) {
                return wsc;
            } 
        }
        if (wsc == null) {
            throw new RuntimeException("Could not find an implementation class.");
        } else {
            throw new RuntimeException("Could not find an implementation class with a non-null WebSocketContainer.");
        }
    }`
显然是无法独立于容器的，毕竟是api接口都依赖容器实现

**Comment by FlowerBirds** [comment]
websocket的服务端是在tomcat容器里面，但是客户端就是一个独立的程序，是可以放在main中，如要放在web容器中，哪还有什么意义，就像js中的websocket与tomcat交互一样，就像访问http服务同理。报错是因为包的原因，具体你得找找，但是跟你说的原因没关系，试试JDK1.7吧
